### ISSUE TITLE
OBS 27.2 Bassasio file not found after update

### ISSUE THREAD

**Issue by cyclemat** [Andersama/obs-asio#111]
Have to try re download the bassasio and copy it in the right folder but the plugin dont find it ! many people have the problem 

https://obsproject.com/forum/threads/obs-studio-bassasio-not-found.153469/#post-562320

**Comment by Andersama** [comment]
Not sure the bass version of the plugin was rebuilt for v27.x, pretty sure the directory for obs to find .dlls changed. Don't remember where, hence why it's "not found". Or..., the update could've removed it, you do have to somewhat manually install the bass asio plugin. Won't matter though if the plugin isn't rebuilt because the abi changed and obs sanity checks some things.

TLDR; where the .dll is supposed to be changed, put it where it's supposed to be you'll get past that error. However if you do, I'm pretty sure you'll find that the plugin won't load in anyway. You'll need to rebuild the plugin yourself for the new version or reinstall an older obs version.

**Comment by cyclemat** [comment]
have installed the old version but the 27.2 was withdrawn but on the next release we must look if the plugin works again and yes i have tried to install the bassasio manualy !

**Comment by Andersama** [comment]
Any chance the Juce based version of the plugin works? You might want to try that one.

**Comment by cyclemat** [comment]
the new update is out will update tonight and test
