### ISSUE TITLE
Compilation question

### ISSUE THREAD

**Issue by walker-WSH** [Andersama/obs-asio#115]
Hi, I am trying to compile this plugin.
As the wiki,  I should compile juce.lib firstly.

I clone JUCE and open the solution. However there is no project of juce.lib.
In the document of Projucer, I don’t find any tips.

Can you give me any idea ?
Many thanks~

![1653982033](https://user-images.githubusercontent.com/18413354/171117023-5ddceab7-1b2d-4e31-8782-4be7c156b06c.png)

![1653981390](https://user-images.githubusercontent.com/18413354/171116992-45625ed0-f083-46bd-b742-dddffd8c8e7f.png)

**Comment by Andersama** [comment]
I don't remember the project structure for Juce. What you want is to compile Juce as a library such that this file:

https://github.com/juce-framework/JUCE/blob/0abbba3b18c3263137eeaeaa11c917a3425ce585/modules/juce_audio_devices/native/juce_win32_ASIO.cpp

Is added as part of the compilation.

To do that you have to define the macro `JUCE_ASIO` as 1 before this header gets included that way the binary gets compiled with ASIO device support. Otherwise you won't be able to scan for asio devices.

https://github.com/juce-framework/JUCE/blob/0abbba3b18c3263137eeaeaa11c917a3425ce585/modules/juce_audio_devices/juce_audio_devices.h

Hope that helps, best of luck.

**Comment by walker-WSH** [comment]
> I don't remember the project structure for Juce. What you want is to compile Juce as a library such that this file:
> 
> https://github.com/juce-framework/JUCE/blob/0abbba3b18c3263137eeaeaa11c917a3425ce585/modules/juce_audio_devices/native/juce_win32_ASIO.cpp
> 
> Is added as part of the compilation.
> 
> To do that you have to define the macro `JUCE_ASIO` as 1 before this header gets included that way the binary gets compiled with ASIO device support. Otherwise you won't be able to scan for asio devices.
> 
> https://github.com/juce-framework/JUCE/blob/0abbba3b18c3263137eeaeaa11c917a3425ce585/modules/juce_audio_devices/juce_audio_devices.h
> 
> Hope that helps, best of luck.

many thinks ~ I will try it again. 
I find the header included in your plugin is "`#include <JuceHeader.h>`" is located in:
`JUCE\extras\WindowsDLL\JuceLibraryCode\JuceHeader.h`
I thinks the WindowsDLL is just the project you said.

**Comment by walker-WSH** [comment]
Here is the steps that I success to compile JUCE with ASIO supported. Hope it can help others.

1. download JUCE code: `https://github.com/juce-framework/JUCE`
2. download  ASIO SDK：`https://www.steinberg.net/developers/`
3. open sln: `JUCE\extras\WindowsDLL\Builds\VisualStudio2022\WindowsDLL.sln`
4. add include path for ASIO SDK: `asiosdk_2.3.3_2019-06-14\common\`
5. search `JUCE_ASIO` in` juce_audio_devices.h `and modiy it with 1;
6. maybe you will meet compile error with C2385, add macro for `class ParameterComponent`：
```
class ParameterComponent : public Component,
                           public ParameterListener
{
public:
    using ParameterListener::ParameterListener;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(ParameterComponent)
};
```

**Comment by Andersama** [comment]
Glad you managed to work it out, and thanks for including instructions.
