### ISSUE TITLE
Feature request: all 16 channels for RODECASTER Pro II / Duo

### ISSUE THREAD

**Issue by Scx8R5SvSlYB3xcM0psn** [Andersama/obs-asio#143]
Hello, I am struggling to record multiple audio tracks using ASIO plugin. The situation is following: RODE in their Rodecaster Pro II and Duo devices are providing a total number of 16 audio channels: 

1 Mix L
2 Mix R
3 XLR/TRS 1
4 XLR/TRS 2
5 XLR/TRS 3
6 XLR/TRS 4
7 Bluetooth L
8 Bluetooth R
9 SMART Pads L
10 SMART Pads R
11 USB Main L
12 USB Main R
13 USB Chat L
14 USB Chat R
15 USB Secondary L
16 USB Secondary R

As today, there can be only selected in total 8 channels when in the the Settings -> Audio -> Main is a 7.1 configuration selected. Then in ASIO input device properties I can choose up to 8 channels from those 16 available. Ideal situation would be to be able to select all of them for later post processing in NLE (for example Davinci Resolve). The Mix pair (1+2) have general mix of all channels but as backup there are separate tracks with clean mic audio, clean BT and so on.

**Comment by jasonseeb** [comment]
I'm unsure where the "Settings-Audio" channels come into play for this one. The asio input is added to the sources area of a scene. Those are for non-asio drivers at the global level.

The second part is also confusing to me but probably because you are talking about a 7.1 channel device, correct? So when you say you can select 8 channels, it's the 7 + 1 channel?

As an example, in my pic you select 7.1 in "Format", and then select those channels altogether in the "OBS Channel 1" spot?
![1](https://github.com/Andersama/obs-asio/assets/134801575/b41f17ef-023f-4a75-8c89-8eef785d29f0)

Just trying to clarify what you mean so I can provide assistance if possible.

**Comment by Scx8R5SvSlYB3xcM0psn** [comment]
I mean when selecting the 7.1 audio, I can chose 8 of the 16 channels
![image](https://github.com/Andersama/obs-asio/assets/9294067/b7e99a64-6ae2-4981-b172-1ccba4464391)

Also then I can record this audio input as multi track
![image](https://github.com/Andersama/obs-asio/assets/9294067/57dc44b4-bfd1-4ed9-8612-beb1109f9e75)

In the video properties I see many channels (but only 8 chosen from 16 existing)
![image](https://github.com/Andersama/obs-asio/assets/9294067/2366441e-1464-4f9a-aa7b-f6017c57d677)

I is almost perfect but why limit the amount of chanels?

**Comment by jasonseeb** [comment]
In the last pic, I only see 6 tracks available, and that's because OBS only allows for recording 6 separate tracks. In that first pic, that's 1 track with all the 7.1 channels in it "Strumien 1"

Right click in the "Audio Mixer" section of OBS then select "Advanced Audio Properties"
![3](https://github.com/Andersama/obs-asio/assets/134801575/625e0103-45bc-4335-8768-263076128300)

There is where you can select which tracks contain which audio sources.

**Comment by Scx8R5SvSlYB3xcM0psn** [comment]
Yes, that's something I didn't notice. The audio track (strumien 1) has 3 front, 2 middle, 2 rear and LFE, that's total 8 channels of audio. All the others are of course not needed.

If I remove all 2-6 channels 
![image](https://github.com/Andersama/obs-asio/assets/9294067/33f7a6ed-9773-493e-be35-484d5a2d45ed)
 
![image](https://github.com/Andersama/obs-asio/assets/9294067/e543904b-7ac3-49d6-bf10-4f023b0a51d0)

then I get the video with only 7.1 channels
![image](https://github.com/Andersama/obs-asio/assets/9294067/b5f77d40-32f2-41df-8884-8c69954b72c9)

But that's bummer that I can't have more channels in the means not 7.1 config, but 2.0 but many streams in the video. Then it would be possible to add more than 8 channels because a video container file can have really many audio tracks (for example movie languages and so on).

**Comment by jasonseeb** [comment]
When using the global audio devices, you are not using the asio plugin just so you are aware. That is all stock OBS without anything extra plugins.

**Comment by pkviet** [comment]
My obs fork supports 16 channels including for asio 
However I haven't updated it since v27.
Maybe I'll update it to 30. But don't count on it on a short run .
Check my repo.
