### ISSUE TITLE
Implement a audio device reset button

### ISSUE THREAD

**Issue by TheRealDadbeard** [Andersama/obs-asio#36]
Hy,

so some ASIO devices like the Voicemeeter Input have some issues being hooked on. That means that I sometimes have to restart OBS a couple of times until the sound is stable and without any distortion. 

The VST host I use (Kushview Elements, it's free and amazing get it) has this button to reset the audio device until it's fine.

Would be neat to have this too in this plugin.

**Comment by pkviet** [comment]
noted. I'll see what can be done.

**Comment by TheRealDadbeard** [comment]
Thanks!

**Comment by chriszuercher** [comment]
@Andersama was this implemented at some point? We sometimes face the problem, that ASIO in OBS stops working when we switch between scenes with and without the ASIO device. We then need to restart OBS and stop the stream. 

I have no idea if the problem is our device (Allen&Heath Qu-24), the asio driver of A&H or OBS. But the possibility to reset ASIO in OBS would probably be a workarround for this.
