### ISSUE TITLE
Zoom H5 only mute

### ISSUE THREAD

**Issue by psander247** [Andersama/obs-asio#55]
Hello, 
I would like to use my Zoom H5 in obs. 
I can select the H5 in Asio settings, but I cant select a channel. There is only "mute" available. 

It worked for one time. But after a restart of obs the channels don´t show up. 

Maybe someone can help me ? 

TIA

**Comment by AspiringFate** [comment]
I am also having this issue with both my Zoom F4 and my Zoom H6. These both used to work before update 25 to OBS.

**Comment by pkviet** [comment]
I need a log .
Since i don't own these devices it's impossible for me to debug without
some infos. Just saying it doesn't work, won't help me fix the problem.

**Comment by AspiringFate** [comment]
Give me like 5 min and I can pull the OBS and the asio driver logs. I will attach a screengrab of the issue we are seeing.

**Comment by AspiringFate** [comment]
[2020-06-18 18-27-24.txt](https://github.com/Andersama/obs-asio/files/4802027/2020-06-18.18-27-24.txt)
![obsASIO_zoom_driver_issue](https://user-images.githubusercontent.com/67131290/85088374-cd8bf880-b194-11ea-9e21-1d5735010d8c.png)

**Comment by AspiringFate** [comment]
There is the screenshot and the OBS Log file

**Comment by pkviet** [comment]
which version works for your device ? obs-asio version and obs-studio version too please

**Comment by AspiringFate** [comment]
I wish I knew how to compile! I, unfortunately, do not. It was working prior with v1.3.1 of obs-aiso and I believe the last time it was working I was on obs version 24.0.6.

**Comment by pkviet** [comment]
i don't know really why it's not working. The log shows an issue connecting to your device.
You're not using your device with another asio app at he same time ?
asio is not multi-client. Some devices bypass this though but most don't.
So if you have a daw open at the same time as obs, it won't work ...

**Comment by pkviet** [comment]
someone in the team has a zoom device; he'll check

**Comment by pkviet** [comment]
so someone else in the obs dev team tested his zoom device and he tells me:
`OBS 25 + ASIO capture audio from Zoom H4n Pro just fine`
I've no idea whats going on w/ your devices

**Comment by AspiringFate** [comment]
No OBS is the only thing open and accesses them at a time. 

al # #
> `OBS 25 + ASIO capture audio from Zoom H4n Pro just fine`

The h4 uses a different driver set because it doesn't have the multi IO ability. When I put them into a stereo mode, OBS picks them up fine. but that disables the ASIO driver side of things that the multi IO driver adds.

I just tried the asio input while having both the h6 and the f4 in stereo mode and it can see them fine. The issue is definitely something between zooms multi asio driver and obs-asio.

**Comment by pkviet** [comment]
there's no change in the code of obs-asio in between the versions I compiled against obs-studio v24 and v25.  Only libobs changed in obs-studio, so this required to relink obs-asio, that's all.
So I have 0 clue as to why it used to work in v24 and not on v25.
I'd need one of these devices to be able to trace in the code.
I'd suggest to try other versions of the plugin (the bassasio version is very good; but since I can't release it, you'll have to find someone who can compile it for you).
