### ISSUE TITLE
Audio Stuttering

### ISSUE THREAD

**Issue by burritodreamer** [Andersama/obs-asio#63]
**My Setup:**
I am  using VoiceMeeter Potato to output 6 channels via VoiceMeeter AUX Virtual VAIO in composite mode. I then use the plugin with 4 instances of the ASIO Input Capture source to capture the audio channels into OBS. 

**The Issue:**
It all works as desired, _sometimes_. Sometimes, I start OBS and it works perfectly. Sometimes when I start OBS, I will get choppy audio immediately, as if the sample rate is incorrect. Other times, it will work fine for a while (up to an hour or so) then start becoming choppy. 

I have the latest version of OBS (26.0.2), and the plugin (2.0.3). I have verified that my interface, VoiceMeeter, and OBS are all set to 44100 Hz. I suspect the issue is with OBS or the plugin, because while monitoring the output via my interface in VoiceMeeter, the sound is not choppy, only the audio output from OBS (recording or streaming).

If any more info is needed please let me know. I hope I can get this sorted out because the plugin is awesome. Thanks!

**Comment by burritodreamer** [comment]
[2020-10-27 18-24-01.txt](https://github.com/Andersama/obs-asio/files/5448712/2020-10-27.18-24-01.txt)
Attached is an OBS log while I'm having the issue.

Thanks!

**Comment by pkviet** [comment]
i suspect voicemeeter driver. Since the plugin works for many devices. Some devices make some assumptions about the loading and require workarounds.
Tbh we can't possibly track all the devices and implement workarounds for faulty drivers. It's a free open source project done on our free time. We don't earn anything from it.
My suggestion would be to try the bassasio version of this plugin but it will require you to compile it since there are licenses issues preventing us to release it (I'm thinking of a workaround though which I'll implement allowing to release, but it won't be any soon)

**Comment by pkviet** [comment]
one suggestion though: increase the buffer on voicemeeter ==> 1024 for instance instead of the default 256
Latency will be higher but you'll have less errors

**Comment by pkviet** [comment]
Andersama suspected you might have had threading issues due to a weak cpu; but the 1700x is actually up to the task. He tells me that he uses voicemeeter and has no issues. I use it occasionally and haven't had issues either.

**Comment by burritodreamer** [comment]
Yeah, I'm now thinking the issue is with some settings in OBS. I tried using Reaper with the Reastream VST plugin to capture audio in OBS, and was still having the same issue. Did a clean install of OBS, hopefully that will fix it. Thanks for your help with this, I really appreciate it!

**Comment by Andersama** [comment]
Issue seem fixed / should I close this?
