### ISSUE TITLE
Audio feed drops out

### ISSUE THREAD

**Issue by gillythekidYT** [Andersama/obs-asio#65]
I think I saw you mention this somewhere, but everything works great until at seemingly random times, feed from my audio device (my mic plugged into a Universal Audio Arrow) will just stop working. I can't see that anything actually crashed but I will just stop getting audio from my mic at random intervals. The only way to get it back is by switching to a different input and then switching BACK to my mic's input (I guess something in the plugin must reload). Is there a fix for this? I know you work on this plugin for free on your own time, but this is the only application that's allowing me to use my interface with OBS and I'm desperate lol.

**Comment by pkviet** [comment]
increase the buffer; it will help.
Try 512 or even 1024. This increases latency but it'll be more stable.

**Comment by gillythekidYT** [comment]
Is there a reason why this is happening? I didn't think anything was overloading because it's connected via thunderbolt 3 while my webcam and other things aren't. I've seen a few people on other posts saying that increasing the buffer size didn't help... if not the buffer, could it be something else? thank you for the response

**Comment by pkviet** [comment]
well, drivers drivers drivers; asio is notorious for a good bunch of badly written drivers. The asio host implementations often include workarounds for select drivers ...
If it doesn't work, it's almost impossible for us to fix that, because it's mostly out of our hands (on top of not owning the said device). As far as my own devices are concerned, they work flawlessly , so ... 
The only thing apart from increasing the buffer that I can suggest is try the bassasio version of our plugin; but it'll require dev knowledge in order to compile it.
I have plans to rewrite it in order to be able to release it. But there's no ETA; I code for fun in my free time , which is scant ...

**Comment by gillythekidYT** [comment]
Yeah, I've just checked my logfile and it doesn't look like I'm reaching a max buffer... could increasing the buffer size still be the workaround in that type of scenario? I wanted to try the bassasio version but I spent hours today attempting to compile it and couldn't...a friend of mine who is pretty good at coding couldn't figure it out either unfortunately. I know it's a shot in the dark, but do you know of anyone I could maybe contact to somehow help me compile this? and yeah, I realize you do this on your spare time. I really appreciate the help!

**Comment by pkviet** [comment]
show up on obs discord and ping me, it'll be easier for troubleshooting, than this back and forth
