### ISSUE TITLE
Plugin not capturing audio with low buffer sizes selected

### ISSUE THREAD

**Issue by DJUnreal** [Andersama/obs-asio#81]
I had to rework my system to get past another issue with other software not being able to handle higher buffer sizes, and as part of this I dropped the buffer sizes right down to 8 samples. The next time I loaded up OBS, the v3 plugin for ASIO capture was not capturing any audio at all. After a lot of troubleshooting, and changing many devices, I discovered that the plugin will only capture audio if the buffer is greater than 64 samples. Furthermore using this plugin as a source for other overlays (eg the spectralizer plugin) has ceased to work since the buffer size change, even after removing and readding. It would appear that changing the buffer size (which you should be able to do with ASIO compliant hardware and software) causes major issues with obs-asio v3.0.0 if you set it to be particularly low, even when other tools (ASIO Link Pro etc) can all capture fine.

Hardware is a Behringer X-Air XR18. Using ASIO Link Pro to map to WDM devices for outputs, but also using OBS-ASIO to talk directly to the hardware for capture. ASIO Link Pro was showing me that the audio paths were all working consistently the whole time, but OBS-ASIO could not 'hear' any audio (the level meters never started to move) unless the buffer size was larger than 64 samples.

**Comment by DJUnreal** [comment]
Log files from tonight's testing:
[2021-03-27 20-29-34.txt](https://github.com/Andersama/obs-asio/files/6216484/2021-03-27.20-29-34.txt)
[2021-03-27 20-39-53.txt](https://github.com/Andersama/obs-asio/files/6216485/2021-03-27.20-39-53.txt)
[2021-03-27 21-10-36.txt](https://github.com/Andersama/obs-asio/files/6216486/2021-03-27.21-10-36.txt)
[2021-03-27 21-13-29.txt](https://github.com/Andersama/obs-asio/files/6216487/2021-03-27.21-13-29.txt)
[2021-03-27 21-19-46.txt](https://github.com/Andersama/obs-asio/files/6216488/2021-03-27.21-19-46.txt)
[2021-03-27 21-28-57.txt](https://github.com/Andersama/obs-asio/files/6216489/2021-03-27.21-28-57.txt)
[2021-03-27 21-34-50.txt](https://github.com/Andersama/obs-asio/files/6216490/2021-03-27.21-34-50.txt)
[2021-03-27 21-48-17.txt](https://github.com/Andersama/obs-asio/files/6216491/2021-03-27.21-48-17.txt)
[2021-03-27 22-05-06.txt](https://github.com/Andersama/obs-asio/files/6216492/2021-03-27.22-05-06.txt)
[2021-03-27 20-23-35.txt](https://github.com/Andersama/obs-asio/files/6216493/2021-03-27.20-23-35.txt)

**Comment by Andersama** [comment]
Don't think I've run into an asio device that does less than 64 samples at a time, given how the api works that's probably absolutely hammering the system with audio callbacks, and I don't think the data structure I used is ideal for a buffer size that small. If your device works in other programs at that low buffer size let me know, Otherwise since I know the internals of obs has a 1024 buffer anyway...I'd stick with what works.

**Comment by Andersama** [comment]
I'd also advise sticking to version 2.0. pkv rereleased older asiobass code as 3.0, so far 2.0 using the juce library's more stable.

**Comment by DJUnreal** [comment]
So I started experimenting with buffer sizes because Zoom and other applications didn't like the higher buffer sizes and they were getting stuttering and popping on the audio. I'm using ASIO Link Pro in order to act as a go-between for the ASIO channels and the corresponding WDM audio devices that other applications can talk to. In terms of native ASIO, I'm not running many/any direct-talking apps except OBS-ASIO at the moment.

Device is a Behringer X-Air XR18, and that allows me to set the buffer size as low as 8 samples, which ASIO Link Pro will allow also.

I'll give v2 a go, and see whether that helps, but if you're able to have support for lower buffer sizes, that'd be awesome

**Comment by Andersama** [comment]
Part of this may be hardware other than just the audio device because this is a model that's pretty much as low latency as it gets.

I wrote I have a temporary buffer to store a couple of double buffers with asio, this gives me headroom to wait for a few asio calls. To me it sounds like a potential approach for me is to ensure a larger temporary buffer and to make sure that lower latency calls are just appended as part of the callback and then only issue one call to process everything together. I'd really rather leave the plugin as is in part because doing the above is really shifting the responsibility the buffer size selection from the hardware to the plugin, because what that change would model is a larger buffer size, and if you're really after that low latency option I'd rather it be wysiwg rather than me silently obfuscating that away. I'm also not entirely sure it's too different from the code that already exists because as it stands it's an additional thread which waits for new fully copied buffers to write over into obs.

**Comment by pkviet** [comment]
I'm also an XR18 user; your buffer of 8 sounds really unreasonable to me. Asio link pro will be limited by WDM latency anyway so at least 20 ms. At 48 kHz, with 8 samples, you're down to 0.17 ms !!! I strongly doubt that this is useful in any setting and this will create a lot of cpu overhead.
Anyway, that'd be a really niche feature given the user base of this plugin. 
 Sorry but we're now in basic maintainance mode, bug fix and don't plan on any extensive rewrite. So I'll close this.
